### ISSUE TITLE
Comunicar al upstream sobre la propuesta

### ISSUE THREAD

**Issue by jamescr** [LabExperimental-SIUA/osmtracker-android#43]
Poner un mensaje en el [issue "osmtracker for special purposes"](https://github.com/nguillaumin/osmtracker-android/issues/85) del upstream, para comentarle que trabajaremos en solucionarlo en dos etapas: (a) facilitar la instalación de layouts personalizados y (b) subir trazas a servidores distintos de osm. 

Luego hacer un issue en el repo del upstream, donde se presente la propuesta de abordaje de (a), utilizar los pantallazos del issue #42  y avisar que estaremos trabajando en eso en el repo del labexp.

**Comment by altaros97** [comment]
@jamescr Le voy a pasar el comentario que tengo que publicar en el issue 85 por aquí para ver si está bien.
>We are developing this Issue in two parts:
A) Facilitate the download and installation of custom Layouts, creating a new activity in the settings menu.
B) Upload traces to different servers, in addition to OSM.  

No sé, si eso es lo que tengo que poner o si tengo que añadir más detalles o si está bien redactado, jaja!

**Comment by jamescr** [comment]
Me parece bien pero sugiero agregar que vamos a comenzar con el paso (a) y
que creará un issue donde compartiremos la propuesta de desarrollo (  luego
hay que hacer eso )



El 05/10/2017 09:06, "José Adrián Amador Ávila" <notifications@github.com>
escribió:

@jamescr <https://github.com/jamescr> Le voy a pasar el comentario que
tengo que publicar en el issue 85 por aquí para ver si está bien.

We are developing this Issue in two parts:
A) Facilitate the download and installation of custom Layouts, creating a
new activity in the settings menu.
B) Upload traces to different servers, in addition to OSM.

No sé, si eso es lo que tengo que poner o si tengo que añadir más detalles
o si está bien redactado, jaja!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/LabExperimental-SIUA/osmtracker-android/issues/43#issuecomment-334494298>,
or mute the thread

**Comment by altaros97** [comment]
Entonces debería de quedar así:

>We are developing this Issue in two parts:
A) Facilitate the download and installation of custom Layouts, creating a new activity in the settings menu.
B) Upload traces to different servers, in addition to OSM.
We are going to start by solving the first part (A), I gonna creat a new Issue where I going to explain our development proposal.

**Comment by altaros97** [comment]
Gracias, aún no se me da bien usar el futuro. Lo voy a publicar hasta que el issue #42 este completo.

**Comment by altaros97** [comment]
Proposed explanation to facilitate the download and installation of Layouts.

As mentioned @jamescr in issue #85, explain the process to a person, who does not have technical knowledge, how to use different Layouts, sometimes can be difficult, that is why we want to add extra functionality to facilitate the work and so anyone can do it without problems.

With the following screenshots I hope to be able to explain the proposal that we are offering to solve this task.

We will change the option of **buttons presets** so that instead of opening a pop-up with the Layouts that can be activated, open a new activity, such as the one shown below

<img src="https://github.com/LabExperimental-SIUA/osmtracker-android/blob/docu/documentaci%C3%B3n/Screenshots/buttons_presets.png?raw=true" alt="buttons presets" />

In this activity we will have three sections, the first is the Layout that comes by default in the application, the second part are the Layouts that we have downloaded and available for installation, these seconds will have options emerging, such as **update and install** and **delete** (the default layout will not have these options). Finally, the third part consists of a button of **add new** which brings us to another activity where we will be able to download new Layouts.

<img src="https://github.com/LabExperimental-SIUA/osmtracker-android/blob/docu/documentaci%C3%B3n/Screenshots/available_layouts.png?raw=true" alt="available layouts" />

This activity shows the available Layouts for download on a specified server (by default Git Hub), the server must follow a structure of folders and files specified to be able to work, see more information in [Guide to create Layout](https://github.com/LabExperimental-SIUA/osmtracker-android/wiki/Gu%C3%ADa-para-crear-Layout)

When a Layout is pressed a description will be displayed in the language of the device (in case the Layout is not in the language of the device it will be given a pop-up with the available languages ​​so that it can display the description in the selected language ), the same window will show the options for **download** or **cancel** (the download will be with the default language or with the selected language).

Also, in the upper right (tool bar), you will have an option to configure the server where you want to download Layouts, if it is invalid an error message will be displayed.

We will be developing this proposal in the [LabExperimental-SIUA repository](https://github.com/LabExperimental-SIUA/osmtracker-android)

**Comment by altaros97** [comment]
@jamescr, @aton1698, @EmmanuelAB esto es lo que voy a colocar en el issue del upstream, por favor revisar para estar seguro que eso fue lo acordado por todos.

**Comment by jamescr** [comment]
etiqueto a @dmunguia quien nos puede ayudar a darle un vistazo.

**Comment by jamescr** [comment]
Hice un pad con el texto propuesto por @altaros97 y algunas modificaciones de forma.   https://pad.riseup.net/p/nEYvvMRmoPVG

Por cierto que va a ser necesario que una vez que terminemos cerremos el issue #39 le encarguemos a @aton1698 que lo traduzca al inglés (le voy a dejar el issue nuevo).

**Comment by altaros97** [comment]
Creo que con eso está perfecto, y si solo faltaría la traducción de página a la que hago referencia para la explicación de las carpetas.

**Comment by jamescr** [comment]
¿En qué quedaron esto?

**Comment by altaros97** [comment]
¡Listo! ya abrí el nuevo issue con la explicación de la propuesta.
